Nové widgety s ikonkami + úpravy
pobo-builder/widget-asset pull request #8
Opened 2023-06-16 14:22 UTC by votechv

2023-06-16 19:29 UTC, smety commented
Ahoj kdyz tak prosim bez tech hornich ikon.

<img width="1048" alt="image" src="https://github.com/pobo-builder/widget-asset/assets/22744053/79e1848f-ad97-4e81-93a7-febdc98a5b25">

2023-06-16 19:33 UTC, smety requested changes

2023-06-16 19:33 UTC, smety commented on index.html
> +      <div class="rc-multiple-ico-in-one__single">
Tady pls bez tech hornich ikon, kdyz tak take vyhodit i element s třídou `.rc-multiple-ico-in-one__single`

<img width="847" alt="image" src="https://github.com/pobo-builder/widget-asset/assets/22744053/6cb4d025-09ce-45ca-be0a-01c07517a506">

2023-06-16 19:33 UTC, smety commented on index.html
> +  <div class="rc-multiple-ico-in-one">
Slo by tady pls zmenit na tridu napr. `rc-inline-image`?  At je to kratsi a min pomlcek.

2023-06-19 10:39 UTC, votechv commented
Přidal jsem rovnou ten widget s nadpisem pro tu Bottegu :)

2023-06-20 17:09 UTC, smety approved these changes

2023-06-20 17:09 UTC, merged